### ISSUE TITLE
[BUG]: filezilla out of date, current version 3.64.0

### ISSUE THREAD

**Issue by superusercode** [ScoopInstaller/Binary#20]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

filezilla

### Expected/Current Behaviour

Updated to latest/not updated

### Steps to Reproduce

```console
scoop search filezilla
```

### Possible Solution

mirror newest version

### Scoop and Buckets Version

```console
n/a
```

### Scoop Config

```console
n/a
```

### PowerShell Version

```console
n/a
```

**Comment by rashil2000** [comment]
Updated.
